name: InfraCheck CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  infra-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go (required to build InfraCheck)
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Build InfraCheck binary
        run: |
          go build -o infra-check ./main.go

      - name: Run InfraCheck on Terraform code
      # run: |
      #   ./infra-check scan terraform ./terraform --format gha --fail-on warn
        run: |
          ./infra-check scan terraform ./terraform --format gha
        continue-on-error: false  # Fail GitHub Action if warn or error

      # scan Ansible and Puppet as well
      - name: Run InfraCheck on Ansible playbooks
        # run: ./infra-check scan ansible ./ansible --format gha --fail-on warn
        run: ./infra-check scan ansible ./ansible --format gha

      # - name: Run InfraCheck on Puppet manifests
      #   run: ./infra-check scan puppet ./puppet --format gha --fail-on warn
